apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multiarch-tuning-operator-bundle
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator-bundle@sha256:c0b0c313f27c59cd46de10ad0df5049742234c4e585d67133743b616f01169ee
        name: container-image
        resources: {}
status: {}
