apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multiarch-tuning-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multiarch-tuning-operator
    app.kubernetes.io/part-of: multiarch-tuning-operator
  name: multiarch-tuning-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multiarch-tuning-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multiarch-tuning-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator@sha256:8cebb293cbceea222d258c495afdb04d9ef3e206e986df6d358849fd4b7fc7a3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
