apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multiarch-tuning-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multiarch-tuning-operator
    app.kubernetes.io/part-of: multiarch-tuning-operator
  name: multiarch-tuning-operator
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app.kubernetes.io/instance: multiarch-tuning-operator
status:
  loadBalancer: {}
